In [2]:
#importing all the necessary built-in libraries that we gonna need
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
#reading our csv file from where it is saved in computer
df = pd.read_csv(r"C:\Users\Anuj Navin\Downloads\7181_10279_compressed_movie_metadata.csv\movie_metadata.csv")

In [4]:
#having a look at our data
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [5]:
#looking at the shape of dataframe row=5043 & column=28
df.shape

(5043, 28)

In [6]:
#displays total number of NaN values in each coulmn(feature)
df.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [8]:
#handling NaN values,simply filling them with unknown and doing other data processing
df['actor_1_name']  = df['actor_1_name'].fillna('unknown')
df['actor_2_name']  = df['actor_2_name'].fillna('unknown')
df['actor_3_name']  = df['actor_3_name'].fillna('unknown')
df['director_name'] = df['director_name'].fillna('unknown')
df['genres']  = df['genres'].str.replace('|',' ')
df['movie_title'] =  df['movie_title'].str.lower()

In [9]:
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action Adventure Fantasy Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action Adventure Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action Adventure Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,unknown,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime Drama Mystery Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama Horror Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy Drama Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [10]:
#having a look at our movie title column
df['movie_title']

0                                                 avatarÂ
1               pirates of the caribbean: at world's endÂ
2                                                spectreÂ
3                                  the dark knight risesÂ
4       star wars: episode vii - the force awakensÂ    ...
                              ...
5038                             signed sealed deliveredÂ
5039                           the followingÂ
5040                                a plague so pleasantÂ
5041                                    shanghai callingÂ
5042                                   my date with drewÂ
Name: movie_title, Length: 5043, dtype: object

In [11]:
#removing duplicate movie titles
df = df.drop_duplicates(['movie_title'])
df.shape

(4917, 28)

In [12]:
df['movie_title']

0                                                 avatarÂ
1               pirates of the caribbean: at world's endÂ
2                                                spectreÂ
3                                  the dark knight risesÂ
4       star wars: episode vii - the force awakensÂ    ...
                              ...
5038                             signed sealed deliveredÂ
5039                           the followingÂ
5040                                a plague so pleasantÂ
5041                                    shanghai callingÂ
5042                                   my date with drewÂ
Name: movie_title, Length: 4917, dtype: object

In [13]:
df['movie_title'].value_counts()

chasing mavericksÂ              1
dallas buyers clubÂ             1
think like a manÂ               1
dark shadowsÂ                   1
high plains drifterÂ            1
                              ..
cry_wolfÂ                       1
nothingÂ                        1
once upon a time in queensÂ     1
on the lineÂ                    1
the prince of tidesÂ            1
Name: movie_title, Length: 4917, dtype: int64

In [17]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action Adventure Fantasy Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action Adventure Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action Adventure Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [16]:
df['movie_title']

0                                                 avatarÂ
1               pirates of the caribbean: at world's endÂ
2                                                spectreÂ
3                                  the dark knight risesÂ
4       star wars: episode vii - the force awakensÂ    ...
                              ...
5038                             signed sealed deliveredÂ
5039                           the followingÂ
5040                                a plague so pleasantÂ
5041                                    shanghai callingÂ
5042                                   my date with drewÂ
Name: movie_title, Length: 4917, dtype: object

In [41]:
#most important step for content based recommender system making a combined column out of director name,actors name,genre etc.
df['comb'] =  df['actor_1_name'] + df['actor_2_name'] + df['actor_2_name'] + df['genres'] + df['director_name']

C:\Users\Anuj Navin\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [42]:
pd.DataFrame(df['comb'])

                                                   comb
0     CCH PounderJoel David MooreJoel David MooreAct...
1     Johnny DeppOrlando BloomOrlando BloomAction Ad...
2     Christoph WaltzRory KinnearRory KinnearAction ...
3     Tom HardyChristian BaleChristian BaleAction Th...
4     Doug WalkerRob WalkerRob WalkerDocumentaryDoug...
...                                                 ...
5038  Eric MabiusDaphne ZunigaDaphne ZunigaComedy Dr...
5039  Natalie ZeaValorie CurryValorie CurryCrime Dra...
5040  Eva BoehnkeMaxwell MoodyMaxwell MoodyDrama Hor...
5041  Alan RuckDaniel HenneyDaniel HenneyComedy Dram...
5042  John AugustBrian HerzlingerBrian HerzlingerDoc...

[4917 rows x 1 columns]

In [43]:
df[['movie_title','comb']]

,movie_title,comb
0,avatar,CCH PounderJoel David MooreJoel David MooreAct...
1,pirates of the caribbean: at world's end,Johnny DeppOrlando BloomOrlando BloomAction Ad...
2,spectre,Christoph WaltzRory KinnearRory KinnearAction ...
3,the dark knight rises,Tom HardyChristian BaleChristian BaleAction Th...
4,star wars: episode vii - the force awakensÂ ...,Doug WalkerRob WalkerRob WalkerDocumentaryDoug...
...,...,...
5038,signed sealed delivered,Eric MabiusDaphne ZunigaDaphne ZunigaComedy Dr...
5039,the following,Natalie ZeaValorie CurryValorie CurryCrime Dra...
5040,a plague so pleasant,Eva BoehnkeMaxwell MoodyMaxwell MoodyDrama Hor...
5041,shanghai calling,Alan RuckDaniel HenneyDaniel HenneyComedy Dram...
5042,my date with drew,John AugustBrian HerzlingerBrian HerzlingerDoc...

In [44]:
#creating an instance of tf-idf vectorizer
cv =  TfidfVectorizer()

In [45]:
df1 = cv.fit_transform(df['comb'])

In [46]:
df1

<4917x17059 sparse matrix of type '<class 'numpy.float64'>'
	with 35325 stored elements in Compressed Sparse Row format>

In [47]:
#calling cosine similiarity here which we use to find how close vectors generated by tf-idf are
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
df1 = pd.DataFrame(cosine_similarity(df1))
df1

,0,1,2,3,4,5,6,7,8,9,...,4907,4908,4909,4910,4911,4912,4913,4914,4915,4916
0,1.000000,0.027319,0.025032,0.0,0.0,0.045252,0.029760,0.027253,0.038466,0.030683,...,0.019981,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
1,0.027319,1.000000,0.031038,0.0,0.0,0.030447,0.036901,0.000000,0.025882,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
2,0.025032,0.031038,1.000000,0.0,0.0,0.027897,0.033811,0.000000,0.023714,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
3,0.000000,0.000000,0.000000,1.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
4,0.000000,0.000000,0.000000,0.0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4912,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,1.0,0.000000,0.0,0.000000,0.0
4913,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.015675,0.0,0.0,0.0,1.000000,0.0,0.015514,0.0
4914,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,1.0,0.000000,0.0
4915,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.116083,...,0.000000,0.0,0.013916,0.0,0.0,0.0,0.015514,0.0,1.000000,0.0
4916,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,1.0

In [49]:
df1.index = df['movie_title']

In [50]:
df1

,0,1,2,3,4,5,6,7,8,9,...,4907,4908,4909,4910,4911,4912,4913,4914,4915,4916
movie_title,,,,,,,,,,,,,,,,,,,,,
avatar,1.000000,0.027319,0.025032,0.0,0.0,0.045252,0.029760,0.027253,0.038466,0.030683,...,0.019981,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
pirates of the caribbean: at world's end,0.027319,1.000000,0.031038,0.0,0.0,0.030447,0.036901,0.000000,0.025882,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
spectre,0.025032,0.031038,1.000000,0.0,0.0,0.027897,0.033811,0.000000,0.023714,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
the dark knight rises,0.000000,0.000000,0.000000,1.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
star wars: episode vii - the force awakens,0.000000,0.000000,0.000000,0.0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
signed sealed delivered,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,1.0,0.000000,0.0,0.000000,0.0
the following,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.015675,0.0,0.0,0.0,1.000000,0.0,0.015514,0.0
a plague so pleasant,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,1.0,0.000000,0.0
shanghai calling,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.116083,...,0.000000,0.0,0.013916,0.0,0.0,0.0,0.015514,0.0,1.000000,0.0
my date with drew,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,1.0

In [51]:
df1.columns = df['movie_title']

In [52]:
df1

movie_title,avatar,pirates of the caribbean: at world's end,spectre,the dark knight rises,star wars: episode vii - the force awakens,john carter,spider-man 3,tangled,avengers: age of ultron,harry potter and the half-blood prince,...,primer,cavite,el mariachi,the mongol king,newlyweds,signed sealed delivered,the following,a plague so pleasant,shanghai calling,my date with drew
movie_title,,,,,,,,,,,,,,,,,,,,,
avatar,1.000000,0.027319,0.025032,0.0,0.0,0.045252,0.029760,0.027253,0.038466,0.030683,...,0.019981,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
pirates of the caribbean: at world's end,0.027319,1.000000,0.031038,0.0,0.0,0.030447,0.036901,0.000000,0.025882,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
spectre,0.025032,0.031038,1.000000,0.0,0.0,0.027897,0.033811,0.000000,0.023714,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
the dark knight rises,0.000000,0.000000,0.000000,1.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
star wars: episode vii - the force awakens,0.000000,0.000000,0.000000,0.0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
signed sealed delivered,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,1.0,0.000000,0.0,0.000000,0.0
the following,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.015675,0.0,0.0,0.0,1.000000,0.0,0.015514,0.0
a plague so pleasant,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,1.0,0.000000,0.0
shanghai calling,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.116083,...,0.000000,0.0,0.013916,0.0,0.0,0.0,0.015514,0.0,1.000000,0.0
my date with drew,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,1.0

In [54]:
#making recommendations for Spectre
df1.loc['spectre'].sort_values(ascending = False)[:20]

movie_title
spectre                                1.000000
skyfall                                0.294718
road to perdition                      0.254784
the legend of tarzan                   0.182967
the imitation game                     0.161372
american beauty                        0.155668
big eyes                               0.153043
revolutionary road                     0.147570
the green hornet                       0.144741
a simple plan                          0.143309
drag me to hell                        0.139456
away we go                             0.137645
evil dead ii                           0.135038
jarhead                                0.133565
no good deed                           0.114324
for your eyes only                     0.038877
cliffhanger                            0.038243
xxx                                    0.037824
yu-gi-oh! duel monstersÂ                0.036173
all is lost                            0.036016
Name: spectre, dtype: float64

In [55]:
def recommend(m):
    m = m.lower()
    print(df1.loc[m].sort_values(ascending = False)[:10])

In [59]:
recommend('the dark knight rises')

movie_title
the dark knight rises                 1.000000
harsh times                           0.402421
the dark knight                       0.288854
insomnia                              0.282568
memento                               0.278983
inception                             0.274531
the prestige                          0.271654
jack reacher                          0.210371
mission: impossible - rogue nation    0.209164
american hustle                       0.177366
Name: the dark knight rises, dtype: float64